name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Docker
        run: cd ./infra && docker-compose up -d
      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --tests --verbose
